# --- !Ups

CREATE TABLE Carts (
 userId VARCHAR(255) NOT NULL,
 prodId INT NOT NULL,
 PRIMARY KEY(userId, prodId),
 FOREIGN KEY(userId) REFERENCES Users(userId) ON DELETE CASCADE ON UPDATE CASCADE,
 FOREIGN KEY(prodId) REFERENCES Products(prodId) ON DELETE CASCADE ON UPDATE CASCADE
);

# --- !Downs

DROP TABLE Carts;