# --- !Ups

CREATE TABLE Orders (
 orderId INT NOT NULL AUTO_INCREMENT,
 userId VARCHAR(255) NOT NULL,
 shippingMetId INT NOT NULL,
 paymentMetId INT NOT NULL,
 orderTime TIMESTAMP NOT NULL DEFAULT NOW(),
 PRIMARY KEY(orderId),
 FOREIGN KEY(userId) REFERENCES Users(userId) ON DELETE CASCADE ON UPDATE CASCADE,
 FOREIGN KEY(shippingMetId) REFERENCES ShippingMethods(shippingMetId) ON DELETE CASCADE ON UPDATE CASCADE,
 FOREIGN KEY(paymentMetId) REFERENCES PaymentMethods(paymentMetId) ON DELETE CASCADE ON UPDATE CASCADE
);

# --- !Downs

DROP TABLE Orders;